language: cpp
cache:
  directories:
addons:
  apt:
    packages:
    - libffi-dev
    - libblocksruntime-dev
    - clang
before_script:
- git clone --depth 1 git://github.com/cambridgehackers/llvm -b release_50atomicc1
env:
  global:
    - CC=/usr/bin/clang
    - CXX=/usr/bin/clang++
    - LDFLAGS="-g -lBlocksRuntime"
    - CFLAGS="-fblocks -g"
    - CXXFLAGS="-fblocks -g" 
    - MAKEFLAGS="-j 2"
script:
- env | grep FLAGS
- mkdir llvm/build; cd llvm/build; CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DLLVM_EXTERNAL_CLANG_SOURCE_DIR:PATH=../../../clang -DLLVM_TARGETS_TO_BUILD=Atomicc -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE="RELEASE" -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_ENABLE_FFI:BOOL=ON -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_INCLUDE_DOCS:BOOL=OFF -DLLVM_ENABLE_DEBUG:BOOL=ON -DCLANG_ENABLE_ARCMT:BOOL=OFF -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF -DLLVM_DEFAULT_TARGET_TRIPLE:STRING="atomicc-unknown-linux-gnu" .. && make
